version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasir-umi-app
    restart: unless-stopped
    environment:      
      APP_PORT: 3001
      RUST_LOG: info
    ports:
      - "3001:3001"
    networks:
      - kasir-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kasir-network:
    driver: bridge
